version: '3.7'

services:

  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    restart: always
  
  proxy:
    container_name: "proxy"
    image: "proxy"
    build: "./proxy"
    restart: always
    networks:
      - default

  web:
    container_name: "backend"
    image: "backend"
    build: "./code"
    env_file:
      - ./code/.env
    links:
      - postgres
    ports:
      - "5000:5000"
    command: flask run
    restart: always
    networks:
      - default
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=admin_dip
      - POSTGRES_USER=admin_dip
      - POSTGRES_DB=dipdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5439:5432
    restart: always
    networks:
      - default

  chrome-driver:
    container_name: "chrome-driver"
    image: selenium/standalone-chrome:88.0
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    restart: always
    networks:
      - default

  lookup:
    container_name: "lookup"
    image: "lookup"
    build: "./services"
    networks:
      - default

  redis:
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data-prod:/var/lib/redis

  worker:
    container_name: "worker"
    image: "worker"
    build: "./code"
    env_file:
      - ./code/.env.local
    links:
      - postgres
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - './code/workers:/code/workers'
      - './celery-queue-prod:/queue'
    networks:
      - default
    depends_on:
      - postgres
      - redis