version: '3.7'

services:

  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
  
  proxy:
    container_name: "proxy"
    image: "proxy"
    build: "./proxy"
    networks:
      - default

  web:
    container_name: "backend"
    image: "backend"
    build: "./code"
    env_file:
      - ./code/.env
    links:
      - postgres
    ports:
      - "5000:5000"
    networks:
      - default
    depends_on:
      - postgres

  postgres:
    container_name: "postgres"
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=admin_dip
      - POSTGRES_USER=admin_dip
      - POSTGRES_DB=dipdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5439:5432
    networks:
      - default

  chrome-driver:
    container_name: "chrome-driver"
    image: selenium/standalone-chrome:88.0
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    networks:
      - default

  lookup:
    container_name: "lookup"
    image: "lookup"
    build: "./services"
    networks:
      - default